### ISSUE TITLE
ffda-domain-director: offline node switches before switch time has passed

### ISSUE THREAD

**Issue by belzebub40k** [freifunk-darmstadt/ffda-packages#4]
Is it desired that a node switches its domain after the offline threshold has passed but not the switch time?

The [check](https://github.com/freifunk-darmstadt/ffda-packages/blob/master/ffda-domain-director/luasrc/usr/bin/ffda-switch-domain#L31) `has_switch_time_passed()` will never be reached as soon as the offline threshold has passed.
```
if not ddutil.is_offline_treshold_reached() then
  if not ddutil.has_switch_time_passed() then
    return
  end
else
  print("Gateways were unreachable for a long time. Assuming domain switch has already happened. Switching now.")
end
```

I know it might not be possible to get an accurate time if the node is rebooted and can't reach a NTP server but I think the switch should not happen when the switch time is set to `-1`.

**Comment by blocktrron** [comment]
@belzebub40k You are absolutely right! I will prepare a fix.

**Comment by blocktrron** [comment]
@belzebub40k Could you check the latest master? This must have been slipped thru while refactoring. :disappointed:

**Comment by belzebub40k** [comment]
@blocktrron compiler is running. I'll report after testing.

**Comment by belzebub40k** [comment]
Works as expected. The node does not switch when offline time is exceeded and switch_after is set to -1.
